/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OverdueRouteImport } from './routes/overdue'
import { Route as InquiriesRouteImport } from './routes/inquiries'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminWhatsappBotRouteImport } from './routes/admin.whatsapp-bot'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as DocumentsTechnicalSubmittalsIndexRouteImport } from './routes/documents.technical-submittals.index'
import { Route as DocumentsSubcontractorApprovalsIndexRouteImport } from './routes/documents.subcontractor-approvals.index'
import { Route as DocumentsShopDrawingsIndexRouteImport } from './routes/documents.shop-drawings.index'
import { Route as DocumentsRfisIndexRouteImport } from './routes/documents.rfis.index'
import { Route as DocumentsNcrsIndexRouteImport } from './routes/documents.ncrs.index'
import { Route as DocumentsMaterialSubmittalsIndexRouteImport } from './routes/documents.material-submittals.index'
import { Route as DocumentsMaterialInspectionRequestsIndexRouteImport } from './routes/documents.material-inspection-requests.index'
import { Route as DocumentsInspectionRequestsIndexRouteImport } from './routes/documents.inspection-requests.index'
import { Route as DocumentsTechnicalSubmittalsIdRouteImport } from './routes/documents.technical-submittals.$id'
import { Route as DocumentsSubcontractorApprovalsIdRouteImport } from './routes/documents.subcontractor-approvals.$id'
import { Route as DocumentsShopDrawingsIdRouteImport } from './routes/documents.shop-drawings.$id'
import { Route as DocumentsRfisIdRouteImport } from './routes/documents.rfis.$id'
import { Route as DocumentsNcrsIdRouteImport } from './routes/documents.ncrs.$id'
import { Route as DocumentsMaterialSubmittalsIdRouteImport } from './routes/documents.material-submittals.$id'
import { Route as DocumentsMaterialInspectionRequestsIdRouteImport } from './routes/documents.material-inspection-requests.$id'
import { Route as DocumentsInspectionRequestsIdRouteImport } from './routes/documents.inspection-requests.$id'

const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OverdueRoute = OverdueRouteImport.update({
  id: '/overdue',
  path: '/overdue',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesRoute = InquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhatsappBotRoute = AdminWhatsappBotRouteImport.update({
  id: '/admin/whatsapp-bot',
  path: '/admin/whatsapp-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsTechnicalSubmittalsIndexRoute =
  DocumentsTechnicalSubmittalsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DocumentsTechnicalSubmittalsRoute,
  } as any)
const DocumentsSubcontractorApprovalsIndexRoute =
  DocumentsSubcontractorApprovalsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DocumentsSubcontractorApprovalsRoute,
  } as any)
const DocumentsShopDrawingsIndexRoute =
  DocumentsShopDrawingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DocumentsShopDrawingsRoute,
  } as any)
const DocumentsRfisIndexRoute = DocumentsRfisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRfisRoute,
} as any)
const DocumentsNcrsIndexRoute = DocumentsNcrsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsNcrsRoute,
} as any)
const DocumentsMaterialSubmittalsIndexRoute =
  DocumentsMaterialSubmittalsIndexRouteImport.update({
    id: '/documents/material-submittals/',
    path: '/documents/material-submittals/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsMaterialInspectionRequestsIndexRoute =
  DocumentsMaterialInspectionRequestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DocumentsMaterialInspectionRequestsRoute,
  } as any)
const DocumentsInspectionRequestsIndexRoute =
  DocumentsInspectionRequestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DocumentsInspectionRequestsRoute,
  } as any)
const DocumentsTechnicalSubmittalsIdRoute =
  DocumentsTechnicalSubmittalsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DocumentsTechnicalSubmittalsRoute,
  } as any)
const DocumentsSubcontractorApprovalsIdRoute =
  DocumentsSubcontractorApprovalsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DocumentsSubcontractorApprovalsRoute,
  } as any)
const DocumentsShopDrawingsIdRoute = DocumentsShopDrawingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocumentsShopDrawingsRoute,
} as any)
const DocumentsRfisIdRoute = DocumentsRfisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocumentsRfisRoute,
} as any)
const DocumentsNcrsIdRoute = DocumentsNcrsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocumentsNcrsRoute,
} as any)
const DocumentsMaterialSubmittalsIdRoute =
  DocumentsMaterialSubmittalsIdRouteImport.update({
    id: '/documents/material-submittals/$id',
    path: '/documents/material-submittals/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsMaterialInspectionRequestsIdRoute =
  DocumentsMaterialInspectionRequestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DocumentsMaterialInspectionRequestsRoute,
  } as any)
const DocumentsInspectionRequestsIdRoute =
  DocumentsInspectionRequestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DocumentsInspectionRequestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inquiries': typeof InquiriesRoute
  '/overdue': typeof OverdueRoute
  '/projects': typeof ProjectsRoute
  '/tenders': typeof TendersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whatsapp-bot': typeof AdminWhatsappBotRoute
  '/documents/inspection-requests/$id': typeof DocumentsInspectionRequestsIdRoute
  '/documents/material-inspection-requests/$id': typeof DocumentsMaterialInspectionRequestsIdRoute
  '/documents/material-submittals/$id': typeof DocumentsMaterialSubmittalsIdRoute
  '/documents/ncrs/$id': typeof DocumentsNcrsIdRoute
  '/documents/rfis/$id': typeof DocumentsRfisIdRoute
  '/documents/shop-drawings/$id': typeof DocumentsShopDrawingsIdRoute
  '/documents/subcontractor-approvals/$id': typeof DocumentsSubcontractorApprovalsIdRoute
  '/documents/technical-submittals/$id': typeof DocumentsTechnicalSubmittalsIdRoute
  '/documents/inspection-requests/': typeof DocumentsInspectionRequestsIndexRoute
  '/documents/material-inspection-requests/': typeof DocumentsMaterialInspectionRequestsIndexRoute
  '/documents/material-submittals/': typeof DocumentsMaterialSubmittalsIndexRoute
  '/documents/ncrs/': typeof DocumentsNcrsIndexRoute
  '/documents/rfis/': typeof DocumentsRfisIndexRoute
  '/documents/shop-drawings/': typeof DocumentsShopDrawingsIndexRoute
  '/documents/subcontractor-approvals/': typeof DocumentsSubcontractorApprovalsIndexRoute
  '/documents/technical-submittals/': typeof DocumentsTechnicalSubmittalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inquiries': typeof InquiriesRoute
  '/overdue': typeof OverdueRoute
  '/projects': typeof ProjectsRoute
  '/tenders': typeof TendersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whatsapp-bot': typeof AdminWhatsappBotRoute
  '/documents/inspection-requests/$id': typeof DocumentsInspectionRequestsIdRoute
  '/documents/material-inspection-requests/$id': typeof DocumentsMaterialInspectionRequestsIdRoute
  '/documents/material-submittals/$id': typeof DocumentsMaterialSubmittalsIdRoute
  '/documents/ncrs/$id': typeof DocumentsNcrsIdRoute
  '/documents/rfis/$id': typeof DocumentsRfisIdRoute
  '/documents/shop-drawings/$id': typeof DocumentsShopDrawingsIdRoute
  '/documents/subcontractor-approvals/$id': typeof DocumentsSubcontractorApprovalsIdRoute
  '/documents/technical-submittals/$id': typeof DocumentsTechnicalSubmittalsIdRoute
  '/documents/inspection-requests': typeof DocumentsInspectionRequestsIndexRoute
  '/documents/material-inspection-requests': typeof DocumentsMaterialInspectionRequestsIndexRoute
  '/documents/material-submittals': typeof DocumentsMaterialSubmittalsIndexRoute
  '/documents/ncrs': typeof DocumentsNcrsIndexRoute
  '/documents/rfis': typeof DocumentsRfisIndexRoute
  '/documents/shop-drawings': typeof DocumentsShopDrawingsIndexRoute
  '/documents/subcontractor-approvals': typeof DocumentsSubcontractorApprovalsIndexRoute
  '/documents/technical-submittals': typeof DocumentsTechnicalSubmittalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inquiries': typeof InquiriesRoute
  '/overdue': typeof OverdueRoute
  '/projects': typeof ProjectsRoute
  '/tenders': typeof TendersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whatsapp-bot': typeof AdminWhatsappBotRoute
  '/documents/inspection-requests/$id': typeof DocumentsInspectionRequestsIdRoute
  '/documents/material-inspection-requests/$id': typeof DocumentsMaterialInspectionRequestsIdRoute
  '/documents/material-submittals/$id': typeof DocumentsMaterialSubmittalsIdRoute
  '/documents/ncrs/$id': typeof DocumentsNcrsIdRoute
  '/documents/rfis/$id': typeof DocumentsRfisIdRoute
  '/documents/shop-drawings/$id': typeof DocumentsShopDrawingsIdRoute
  '/documents/subcontractor-approvals/$id': typeof DocumentsSubcontractorApprovalsIdRoute
  '/documents/technical-submittals/$id': typeof DocumentsTechnicalSubmittalsIdRoute
  '/documents/inspection-requests/': typeof DocumentsInspectionRequestsIndexRoute
  '/documents/material-inspection-requests/': typeof DocumentsMaterialInspectionRequestsIndexRoute
  '/documents/material-submittals/': typeof DocumentsMaterialSubmittalsIndexRoute
  '/documents/ncrs/': typeof DocumentsNcrsIndexRoute
  '/documents/rfis/': typeof DocumentsRfisIndexRoute
  '/documents/shop-drawings/': typeof DocumentsShopDrawingsIndexRoute
  '/documents/subcontractor-approvals/': typeof DocumentsSubcontractorApprovalsIndexRoute
  '/documents/technical-submittals/': typeof DocumentsTechnicalSubmittalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inquiries'
    | '/overdue'
    | '/projects'
    | '/tenders'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/whatsapp-bot'
    | '/documents/inspection-requests/$id'
    | '/documents/material-inspection-requests/$id'
    | '/documents/material-submittals/$id'
    | '/documents/ncrs/$id'
    | '/documents/rfis/$id'
    | '/documents/shop-drawings/$id'
    | '/documents/subcontractor-approvals/$id'
    | '/documents/technical-submittals/$id'
    | '/documents/inspection-requests/'
    | '/documents/material-inspection-requests/'
    | '/documents/material-submittals/'
    | '/documents/ncrs/'
    | '/documents/rfis/'
    | '/documents/shop-drawings/'
    | '/documents/subcontractor-approvals/'
    | '/documents/technical-submittals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inquiries'
    | '/overdue'
    | '/projects'
    | '/tenders'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/whatsapp-bot'
    | '/documents/inspection-requests/$id'
    | '/documents/material-inspection-requests/$id'
    | '/documents/material-submittals/$id'
    | '/documents/ncrs/$id'
    | '/documents/rfis/$id'
    | '/documents/shop-drawings/$id'
    | '/documents/subcontractor-approvals/$id'
    | '/documents/technical-submittals/$id'
    | '/documents/inspection-requests'
    | '/documents/material-inspection-requests'
    | '/documents/material-submittals'
    | '/documents/ncrs'
    | '/documents/rfis'
    | '/documents/shop-drawings'
    | '/documents/subcontractor-approvals'
    | '/documents/technical-submittals'
  id:
    | '__root__'
    | '/'
    | '/inquiries'
    | '/overdue'
    | '/projects'
    | '/tenders'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/whatsapp-bot'
    | '/documents/inspection-requests/$id'
    | '/documents/material-inspection-requests/$id'
    | '/documents/material-submittals/$id'
    | '/documents/ncrs/$id'
    | '/documents/rfis/$id'
    | '/documents/shop-drawings/$id'
    | '/documents/subcontractor-approvals/$id'
    | '/documents/technical-submittals/$id'
    | '/documents/inspection-requests/'
    | '/documents/material-inspection-requests/'
    | '/documents/material-submittals/'
    | '/documents/ncrs/'
    | '/documents/rfis/'
    | '/documents/shop-drawings/'
    | '/documents/subcontractor-approvals/'
    | '/documents/technical-submittals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InquiriesRoute: typeof InquiriesRoute
  OverdueRoute: typeof OverdueRoute
  ProjectsRoute: typeof ProjectsRoute
  TendersRoute: typeof TendersRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWhatsappBotRoute: typeof AdminWhatsappBotRoute
  DocumentsMaterialSubmittalsIdRoute: typeof DocumentsMaterialSubmittalsIdRoute
  DocumentsMaterialSubmittalsIndexRoute: typeof DocumentsMaterialSubmittalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overdue': {
      id: '/overdue'
      path: '/overdue'
      fullPath: '/overdue'
      preLoaderRoute: typeof OverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries': {
      id: '/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof InquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whatsapp-bot': {
      id: '/admin/whatsapp-bot'
      path: '/admin/whatsapp-bot'
      fullPath: '/admin/whatsapp-bot'
      preLoaderRoute: typeof AdminWhatsappBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/technical-submittals/': {
      id: '/documents/technical-submittals/'
      path: '/'
      fullPath: '/documents/technical-submittals/'
      preLoaderRoute: typeof DocumentsTechnicalSubmittalsIndexRouteImport
      parentRoute: typeof DocumentsTechnicalSubmittalsRoute
    }
    '/documents/subcontractor-approvals/': {
      id: '/documents/subcontractor-approvals/'
      path: '/'
      fullPath: '/documents/subcontractor-approvals/'
      preLoaderRoute: typeof DocumentsSubcontractorApprovalsIndexRouteImport
      parentRoute: typeof DocumentsSubcontractorApprovalsRoute
    }
    '/documents/shop-drawings/': {
      id: '/documents/shop-drawings/'
      path: '/'
      fullPath: '/documents/shop-drawings/'
      preLoaderRoute: typeof DocumentsShopDrawingsIndexRouteImport
      parentRoute: typeof DocumentsShopDrawingsRoute
    }
    '/documents/rfis/': {
      id: '/documents/rfis/'
      path: '/'
      fullPath: '/documents/rfis/'
      preLoaderRoute: typeof DocumentsRfisIndexRouteImport
      parentRoute: typeof DocumentsRfisRoute
    }
    '/documents/ncrs/': {
      id: '/documents/ncrs/'
      path: '/'
      fullPath: '/documents/ncrs/'
      preLoaderRoute: typeof DocumentsNcrsIndexRouteImport
      parentRoute: typeof DocumentsNcrsRoute
    }
    '/documents/material-submittals/': {
      id: '/documents/material-submittals/'
      path: '/documents/material-submittals'
      fullPath: '/documents/material-submittals/'
      preLoaderRoute: typeof DocumentsMaterialSubmittalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/material-inspection-requests/': {
      id: '/documents/material-inspection-requests/'
      path: '/'
      fullPath: '/documents/material-inspection-requests/'
      preLoaderRoute: typeof DocumentsMaterialInspectionRequestsIndexRouteImport
      parentRoute: typeof DocumentsMaterialInspectionRequestsRoute
    }
    '/documents/inspection-requests/': {
      id: '/documents/inspection-requests/'
      path: '/'
      fullPath: '/documents/inspection-requests/'
      preLoaderRoute: typeof DocumentsInspectionRequestsIndexRouteImport
      parentRoute: typeof DocumentsInspectionRequestsRoute
    }
    '/documents/technical-submittals/$id': {
      id: '/documents/technical-submittals/$id'
      path: '/$id'
      fullPath: '/documents/technical-submittals/$id'
      preLoaderRoute: typeof DocumentsTechnicalSubmittalsIdRouteImport
      parentRoute: typeof DocumentsTechnicalSubmittalsRoute
    }
    '/documents/subcontractor-approvals/$id': {
      id: '/documents/subcontractor-approvals/$id'
      path: '/$id'
      fullPath: '/documents/subcontractor-approvals/$id'
      preLoaderRoute: typeof DocumentsSubcontractorApprovalsIdRouteImport
      parentRoute: typeof DocumentsSubcontractorApprovalsRoute
    }
    '/documents/shop-drawings/$id': {
      id: '/documents/shop-drawings/$id'
      path: '/$id'
      fullPath: '/documents/shop-drawings/$id'
      preLoaderRoute: typeof DocumentsShopDrawingsIdRouteImport
      parentRoute: typeof DocumentsShopDrawingsRoute
    }
    '/documents/rfis/$id': {
      id: '/documents/rfis/$id'
      path: '/$id'
      fullPath: '/documents/rfis/$id'
      preLoaderRoute: typeof DocumentsRfisIdRouteImport
      parentRoute: typeof DocumentsRfisRoute
    }
    '/documents/ncrs/$id': {
      id: '/documents/ncrs/$id'
      path: '/$id'
      fullPath: '/documents/ncrs/$id'
      preLoaderRoute: typeof DocumentsNcrsIdRouteImport
      parentRoute: typeof DocumentsNcrsRoute
    }
    '/documents/material-submittals/$id': {
      id: '/documents/material-submittals/$id'
      path: '/documents/material-submittals/$id'
      fullPath: '/documents/material-submittals/$id'
      preLoaderRoute: typeof DocumentsMaterialSubmittalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/material-inspection-requests/$id': {
      id: '/documents/material-inspection-requests/$id'
      path: '/$id'
      fullPath: '/documents/material-inspection-requests/$id'
      preLoaderRoute: typeof DocumentsMaterialInspectionRequestsIdRouteImport
      parentRoute: typeof DocumentsMaterialInspectionRequestsRoute
    }
    '/documents/inspection-requests/$id': {
      id: '/documents/inspection-requests/$id'
      path: '/$id'
      fullPath: '/documents/inspection-requests/$id'
      preLoaderRoute: typeof DocumentsInspectionRequestsIdRouteImport
      parentRoute: typeof DocumentsInspectionRequestsRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InquiriesRoute: InquiriesRoute,
  OverdueRoute: OverdueRoute,
  ProjectsRoute: ProjectsRoute,
  TendersRoute: TendersRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWhatsappBotRoute: AdminWhatsappBotRoute,
  DocumentsMaterialSubmittalsIdRoute: DocumentsMaterialSubmittalsIdRoute,
  DocumentsMaterialSubmittalsIndexRoute: DocumentsMaterialSubmittalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
