/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as ServerErrorRouteImport } from './routes/server-error'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OverdueRouteImport } from './routes/overdue'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InquiriesRouteImport } from './routes/inquiries'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DailyReportsRouteImport } from './routes/daily-reports'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TendersIdRouteImport } from './routes/tenders.$id'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as AdminWhatsappBotRouteImport } from './routes/admin.whatsapp-bot'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as DocumentsTechnicalSubmittalsIndexRouteImport } from './routes/documents.technical-submittals.index'
import { Route as DocumentsSubcontractorApprovalsIndexRouteImport } from './routes/documents.subcontractor-approvals.index'
import { Route as DocumentsShopDrawingsIndexRouteImport } from './routes/documents.shop-drawings.index'
import { Route as DocumentsRfisIndexRouteImport } from './routes/documents.rfis.index'
import { Route as DocumentsNcrsIndexRouteImport } from './routes/documents.ncrs.index'
import { Route as DocumentsMaterialSubmittalsIndexRouteImport } from './routes/documents.material-submittals.index'
import { Route as DocumentsMaterialInspectionRequestsIndexRouteImport } from './routes/documents.material-inspection-requests.index'
import { Route as DocumentsInspectionRequestsIndexRouteImport } from './routes/documents.inspection-requests.index'
import { Route as DocumentsTechnicalSubmittalsIdRouteImport } from './routes/documents.technical-submittals.$id'
import { Route as DocumentsSubcontractorApprovalsIdRouteImport } from './routes/documents.subcontractor-approvals.$id'
import { Route as DocumentsShopDrawingsIdRouteImport } from './routes/documents.shop-drawings.$id'
import { Route as DocumentsRfisIdRouteImport } from './routes/documents.rfis.$id'
import { Route as DocumentsNcrsIdRouteImport } from './routes/documents.ncrs.$id'
import { Route as DocumentsMaterialSubmittalsIdRouteImport } from './routes/documents.material-submittals.$id'
import { Route as DocumentsMaterialInspectionRequestsIdRouteImport } from './routes/documents.material-inspection-requests.$id'
import { Route as DocumentsInspectionRequestsIdRouteImport } from './routes/documents.inspection-requests.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerErrorRoute = ServerErrorRouteImport.update({
  id: '/server-error',
  path: '/server-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OverdueRoute = OverdueRouteImport.update({
  id: '/overdue',
  path: '/overdue',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesRoute = InquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyReportsRoute = DailyReportsRouteImport.update({
  id: '/daily-reports',
  path: '/daily-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersIdRoute = TendersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TendersRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const AdminWhatsappBotRoute = AdminWhatsappBotRouteImport.update({
  id: '/admin/whatsapp-bot',
  path: '/admin/whatsapp-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsTechnicalSubmittalsIndexRoute =
  DocumentsTechnicalSubmittalsIndexRouteImport.update({
    id: '/documents/technical-submittals/',
    path: '/documents/technical-submittals/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsSubcontractorApprovalsIndexRoute =
  DocumentsSubcontractorApprovalsIndexRouteImport.update({
    id: '/documents/subcontractor-approvals/',
    path: '/documents/subcontractor-approvals/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsShopDrawingsIndexRoute =
  DocumentsShopDrawingsIndexRouteImport.update({
    id: '/documents/shop-drawings/',
    path: '/documents/shop-drawings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsRfisIndexRoute = DocumentsRfisIndexRouteImport.update({
  id: '/documents/rfis/',
  path: '/documents/rfis/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsNcrsIndexRoute = DocumentsNcrsIndexRouteImport.update({
  id: '/documents/ncrs/',
  path: '/documents/ncrs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsMaterialSubmittalsIndexRoute =
  DocumentsMaterialSubmittalsIndexRouteImport.update({
    id: '/documents/material-submittals/',
    path: '/documents/material-submittals/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsMaterialInspectionRequestsIndexRoute =
  DocumentsMaterialInspectionRequestsIndexRouteImport.update({
    id: '/documents/material-inspection-requests/',
    path: '/documents/material-inspection-requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsInspectionRequestsIndexRoute =
  DocumentsInspectionRequestsIndexRouteImport.update({
    id: '/documents/inspection-requests/',
    path: '/documents/inspection-requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsTechnicalSubmittalsIdRoute =
  DocumentsTechnicalSubmittalsIdRouteImport.update({
    id: '/documents/technical-submittals/$id',
    path: '/documents/technical-submittals/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsSubcontractorApprovalsIdRoute =
  DocumentsSubcontractorApprovalsIdRouteImport.update({
    id: '/documents/subcontractor-approvals/$id',
    path: '/documents/subcontractor-approvals/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsShopDrawingsIdRoute = DocumentsShopDrawingsIdRouteImport.update({
  id: '/documents/shop-drawings/$id',
  path: '/documents/shop-drawings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRfisIdRoute = DocumentsRfisIdRouteImport.update({
  id: '/documents/rfis/$id',
  path: '/documents/rfis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsNcrsIdRoute = DocumentsNcrsIdRouteImport.update({
  id: '/documents/ncrs/$id',
  path: '/documents/ncrs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsMaterialSubmittalsIdRoute =
  DocumentsMaterialSubmittalsIdRouteImport.update({
    id: '/documents/material-submittals/$id',
    path: '/documents/material-submittals/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsMaterialInspectionRequestsIdRoute =
  DocumentsMaterialInspectionRequestsIdRouteImport.update({
    id: '/documents/material-inspection-requests/$id',
    path: '/documents/material-inspection-requests/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsInspectionRequestsIdRoute =
  DocumentsInspectionRequestsIdRouteImport.update({
    id: '/documents/inspection-requests/$id',
    path: '/documents/inspection-requests/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily-reports': typeof DailyReportsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inquiries': typeof InquiriesRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/overdue': typeof OverdueRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/server-error': typeof ServerErrorRoute
  '/session-expired': typeof SessionExpiredRoute
  '/tenders': typeof TendersRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whatsapp-bot': typeof AdminWhatsappBotRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tenders/$id': typeof TendersIdRoute
  '/documents/inspection-requests/$id': typeof DocumentsInspectionRequestsIdRoute
  '/documents/material-inspection-requests/$id': typeof DocumentsMaterialInspectionRequestsIdRoute
  '/documents/material-submittals/$id': typeof DocumentsMaterialSubmittalsIdRoute
  '/documents/ncrs/$id': typeof DocumentsNcrsIdRoute
  '/documents/rfis/$id': typeof DocumentsRfisIdRoute
  '/documents/shop-drawings/$id': typeof DocumentsShopDrawingsIdRoute
  '/documents/subcontractor-approvals/$id': typeof DocumentsSubcontractorApprovalsIdRoute
  '/documents/technical-submittals/$id': typeof DocumentsTechnicalSubmittalsIdRoute
  '/documents/inspection-requests/': typeof DocumentsInspectionRequestsIndexRoute
  '/documents/material-inspection-requests/': typeof DocumentsMaterialInspectionRequestsIndexRoute
  '/documents/material-submittals/': typeof DocumentsMaterialSubmittalsIndexRoute
  '/documents/ncrs/': typeof DocumentsNcrsIndexRoute
  '/documents/rfis/': typeof DocumentsRfisIndexRoute
  '/documents/shop-drawings/': typeof DocumentsShopDrawingsIndexRoute
  '/documents/subcontractor-approvals/': typeof DocumentsSubcontractorApprovalsIndexRoute
  '/documents/technical-submittals/': typeof DocumentsTechnicalSubmittalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily-reports': typeof DailyReportsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inquiries': typeof InquiriesRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/overdue': typeof OverdueRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/server-error': typeof ServerErrorRoute
  '/session-expired': typeof SessionExpiredRoute
  '/tenders': typeof TendersRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whatsapp-bot': typeof AdminWhatsappBotRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tenders/$id': typeof TendersIdRoute
  '/documents/inspection-requests/$id': typeof DocumentsInspectionRequestsIdRoute
  '/documents/material-inspection-requests/$id': typeof DocumentsMaterialInspectionRequestsIdRoute
  '/documents/material-submittals/$id': typeof DocumentsMaterialSubmittalsIdRoute
  '/documents/ncrs/$id': typeof DocumentsNcrsIdRoute
  '/documents/rfis/$id': typeof DocumentsRfisIdRoute
  '/documents/shop-drawings/$id': typeof DocumentsShopDrawingsIdRoute
  '/documents/subcontractor-approvals/$id': typeof DocumentsSubcontractorApprovalsIdRoute
  '/documents/technical-submittals/$id': typeof DocumentsTechnicalSubmittalsIdRoute
  '/documents/inspection-requests': typeof DocumentsInspectionRequestsIndexRoute
  '/documents/material-inspection-requests': typeof DocumentsMaterialInspectionRequestsIndexRoute
  '/documents/material-submittals': typeof DocumentsMaterialSubmittalsIndexRoute
  '/documents/ncrs': typeof DocumentsNcrsIndexRoute
  '/documents/rfis': typeof DocumentsRfisIndexRoute
  '/documents/shop-drawings': typeof DocumentsShopDrawingsIndexRoute
  '/documents/subcontractor-approvals': typeof DocumentsSubcontractorApprovalsIndexRoute
  '/documents/technical-submittals': typeof DocumentsTechnicalSubmittalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily-reports': typeof DailyReportsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inquiries': typeof InquiriesRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/overdue': typeof OverdueRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/server-error': typeof ServerErrorRoute
  '/session-expired': typeof SessionExpiredRoute
  '/tenders': typeof TendersRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whatsapp-bot': typeof AdminWhatsappBotRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tenders/$id': typeof TendersIdRoute
  '/documents/inspection-requests/$id': typeof DocumentsInspectionRequestsIdRoute
  '/documents/material-inspection-requests/$id': typeof DocumentsMaterialInspectionRequestsIdRoute
  '/documents/material-submittals/$id': typeof DocumentsMaterialSubmittalsIdRoute
  '/documents/ncrs/$id': typeof DocumentsNcrsIdRoute
  '/documents/rfis/$id': typeof DocumentsRfisIdRoute
  '/documents/shop-drawings/$id': typeof DocumentsShopDrawingsIdRoute
  '/documents/subcontractor-approvals/$id': typeof DocumentsSubcontractorApprovalsIdRoute
  '/documents/technical-submittals/$id': typeof DocumentsTechnicalSubmittalsIdRoute
  '/documents/inspection-requests/': typeof DocumentsInspectionRequestsIndexRoute
  '/documents/material-inspection-requests/': typeof DocumentsMaterialInspectionRequestsIndexRoute
  '/documents/material-submittals/': typeof DocumentsMaterialSubmittalsIndexRoute
  '/documents/ncrs/': typeof DocumentsNcrsIndexRoute
  '/documents/rfis/': typeof DocumentsRfisIndexRoute
  '/documents/shop-drawings/': typeof DocumentsShopDrawingsIndexRoute
  '/documents/subcontractor-approvals/': typeof DocumentsSubcontractorApprovalsIndexRoute
  '/documents/technical-submittals/': typeof DocumentsTechnicalSubmittalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily-reports'
    | '/forgot-password'
    | '/inquiries'
    | '/login'
    | '/maintenance'
    | '/offline'
    | '/overdue'
    | '/projects'
    | '/schedule'
    | '/server-error'
    | '/session-expired'
    | '/tenders'
    | '/unauthorized'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/whatsapp-bot'
    | '/projects/$id'
    | '/tenders/$id'
    | '/documents/inspection-requests/$id'
    | '/documents/material-inspection-requests/$id'
    | '/documents/material-submittals/$id'
    | '/documents/ncrs/$id'
    | '/documents/rfis/$id'
    | '/documents/shop-drawings/$id'
    | '/documents/subcontractor-approvals/$id'
    | '/documents/technical-submittals/$id'
    | '/documents/inspection-requests/'
    | '/documents/material-inspection-requests/'
    | '/documents/material-submittals/'
    | '/documents/ncrs/'
    | '/documents/rfis/'
    | '/documents/shop-drawings/'
    | '/documents/subcontractor-approvals/'
    | '/documents/technical-submittals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily-reports'
    | '/forgot-password'
    | '/inquiries'
    | '/login'
    | '/maintenance'
    | '/offline'
    | '/overdue'
    | '/projects'
    | '/schedule'
    | '/server-error'
    | '/session-expired'
    | '/tenders'
    | '/unauthorized'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/whatsapp-bot'
    | '/projects/$id'
    | '/tenders/$id'
    | '/documents/inspection-requests/$id'
    | '/documents/material-inspection-requests/$id'
    | '/documents/material-submittals/$id'
    | '/documents/ncrs/$id'
    | '/documents/rfis/$id'
    | '/documents/shop-drawings/$id'
    | '/documents/subcontractor-approvals/$id'
    | '/documents/technical-submittals/$id'
    | '/documents/inspection-requests'
    | '/documents/material-inspection-requests'
    | '/documents/material-submittals'
    | '/documents/ncrs'
    | '/documents/rfis'
    | '/documents/shop-drawings'
    | '/documents/subcontractor-approvals'
    | '/documents/technical-submittals'
  id:
    | '__root__'
    | '/'
    | '/daily-reports'
    | '/forgot-password'
    | '/inquiries'
    | '/login'
    | '/maintenance'
    | '/offline'
    | '/overdue'
    | '/projects'
    | '/schedule'
    | '/server-error'
    | '/session-expired'
    | '/tenders'
    | '/unauthorized'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/whatsapp-bot'
    | '/projects/$id'
    | '/tenders/$id'
    | '/documents/inspection-requests/$id'
    | '/documents/material-inspection-requests/$id'
    | '/documents/material-submittals/$id'
    | '/documents/ncrs/$id'
    | '/documents/rfis/$id'
    | '/documents/shop-drawings/$id'
    | '/documents/subcontractor-approvals/$id'
    | '/documents/technical-submittals/$id'
    | '/documents/inspection-requests/'
    | '/documents/material-inspection-requests/'
    | '/documents/material-submittals/'
    | '/documents/ncrs/'
    | '/documents/rfis/'
    | '/documents/shop-drawings/'
    | '/documents/subcontractor-approvals/'
    | '/documents/technical-submittals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyReportsRoute: typeof DailyReportsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InquiriesRoute: typeof InquiriesRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OfflineRoute: typeof OfflineRoute
  OverdueRoute: typeof OverdueRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ScheduleRoute: typeof ScheduleRoute
  ServerErrorRoute: typeof ServerErrorRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  TendersRoute: typeof TendersRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWhatsappBotRoute: typeof AdminWhatsappBotRoute
  DocumentsInspectionRequestsIdRoute: typeof DocumentsInspectionRequestsIdRoute
  DocumentsMaterialInspectionRequestsIdRoute: typeof DocumentsMaterialInspectionRequestsIdRoute
  DocumentsMaterialSubmittalsIdRoute: typeof DocumentsMaterialSubmittalsIdRoute
  DocumentsNcrsIdRoute: typeof DocumentsNcrsIdRoute
  DocumentsRfisIdRoute: typeof DocumentsRfisIdRoute
  DocumentsShopDrawingsIdRoute: typeof DocumentsShopDrawingsIdRoute
  DocumentsSubcontractorApprovalsIdRoute: typeof DocumentsSubcontractorApprovalsIdRoute
  DocumentsTechnicalSubmittalsIdRoute: typeof DocumentsTechnicalSubmittalsIdRoute
  DocumentsInspectionRequestsIndexRoute: typeof DocumentsInspectionRequestsIndexRoute
  DocumentsMaterialInspectionRequestsIndexRoute: typeof DocumentsMaterialInspectionRequestsIndexRoute
  DocumentsMaterialSubmittalsIndexRoute: typeof DocumentsMaterialSubmittalsIndexRoute
  DocumentsNcrsIndexRoute: typeof DocumentsNcrsIndexRoute
  DocumentsRfisIndexRoute: typeof DocumentsRfisIndexRoute
  DocumentsShopDrawingsIndexRoute: typeof DocumentsShopDrawingsIndexRoute
  DocumentsSubcontractorApprovalsIndexRoute: typeof DocumentsSubcontractorApprovalsIndexRoute
  DocumentsTechnicalSubmittalsIndexRoute: typeof DocumentsTechnicalSubmittalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-error': {
      id: '/server-error'
      path: '/server-error'
      fullPath: '/server-error'
      preLoaderRoute: typeof ServerErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overdue': {
      id: '/overdue'
      path: '/overdue'
      fullPath: '/overdue'
      preLoaderRoute: typeof OverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries': {
      id: '/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof InquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-reports': {
      id: '/daily-reports'
      path: '/daily-reports'
      fullPath: '/daily-reports'
      preLoaderRoute: typeof DailyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders/$id': {
      id: '/tenders/$id'
      path: '/$id'
      fullPath: '/tenders/$id'
      preLoaderRoute: typeof TendersIdRouteImport
      parentRoute: typeof TendersRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/admin/whatsapp-bot': {
      id: '/admin/whatsapp-bot'
      path: '/admin/whatsapp-bot'
      fullPath: '/admin/whatsapp-bot'
      preLoaderRoute: typeof AdminWhatsappBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/technical-submittals/': {
      id: '/documents/technical-submittals/'
      path: '/documents/technical-submittals'
      fullPath: '/documents/technical-submittals/'
      preLoaderRoute: typeof DocumentsTechnicalSubmittalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/subcontractor-approvals/': {
      id: '/documents/subcontractor-approvals/'
      path: '/documents/subcontractor-approvals'
      fullPath: '/documents/subcontractor-approvals/'
      preLoaderRoute: typeof DocumentsSubcontractorApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/shop-drawings/': {
      id: '/documents/shop-drawings/'
      path: '/documents/shop-drawings'
      fullPath: '/documents/shop-drawings/'
      preLoaderRoute: typeof DocumentsShopDrawingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/rfis/': {
      id: '/documents/rfis/'
      path: '/documents/rfis'
      fullPath: '/documents/rfis/'
      preLoaderRoute: typeof DocumentsRfisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/ncrs/': {
      id: '/documents/ncrs/'
      path: '/documents/ncrs'
      fullPath: '/documents/ncrs/'
      preLoaderRoute: typeof DocumentsNcrsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/material-submittals/': {
      id: '/documents/material-submittals/'
      path: '/documents/material-submittals'
      fullPath: '/documents/material-submittals/'
      preLoaderRoute: typeof DocumentsMaterialSubmittalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/material-inspection-requests/': {
      id: '/documents/material-inspection-requests/'
      path: '/documents/material-inspection-requests'
      fullPath: '/documents/material-inspection-requests/'
      preLoaderRoute: typeof DocumentsMaterialInspectionRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/inspection-requests/': {
      id: '/documents/inspection-requests/'
      path: '/documents/inspection-requests'
      fullPath: '/documents/inspection-requests/'
      preLoaderRoute: typeof DocumentsInspectionRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/technical-submittals/$id': {
      id: '/documents/technical-submittals/$id'
      path: '/documents/technical-submittals/$id'
      fullPath: '/documents/technical-submittals/$id'
      preLoaderRoute: typeof DocumentsTechnicalSubmittalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/subcontractor-approvals/$id': {
      id: '/documents/subcontractor-approvals/$id'
      path: '/documents/subcontractor-approvals/$id'
      fullPath: '/documents/subcontractor-approvals/$id'
      preLoaderRoute: typeof DocumentsSubcontractorApprovalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/shop-drawings/$id': {
      id: '/documents/shop-drawings/$id'
      path: '/documents/shop-drawings/$id'
      fullPath: '/documents/shop-drawings/$id'
      preLoaderRoute: typeof DocumentsShopDrawingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/rfis/$id': {
      id: '/documents/rfis/$id'
      path: '/documents/rfis/$id'
      fullPath: '/documents/rfis/$id'
      preLoaderRoute: typeof DocumentsRfisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/ncrs/$id': {
      id: '/documents/ncrs/$id'
      path: '/documents/ncrs/$id'
      fullPath: '/documents/ncrs/$id'
      preLoaderRoute: typeof DocumentsNcrsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/material-submittals/$id': {
      id: '/documents/material-submittals/$id'
      path: '/documents/material-submittals/$id'
      fullPath: '/documents/material-submittals/$id'
      preLoaderRoute: typeof DocumentsMaterialSubmittalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/material-inspection-requests/$id': {
      id: '/documents/material-inspection-requests/$id'
      path: '/documents/material-inspection-requests/$id'
      fullPath: '/documents/material-inspection-requests/$id'
      preLoaderRoute: typeof DocumentsMaterialInspectionRequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/inspection-requests/$id': {
      id: '/documents/inspection-requests/$id'
      path: '/documents/inspection-requests/$id'
      fullPath: '/documents/inspection-requests/$id'
      preLoaderRoute: typeof DocumentsInspectionRequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface TendersRouteChildren {
  TendersIdRoute: typeof TendersIdRoute
}

const TendersRouteChildren: TendersRouteChildren = {
  TendersIdRoute: TendersIdRoute,
}

const TendersRouteWithChildren =
  TendersRoute._addFileChildren(TendersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyReportsRoute: DailyReportsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InquiriesRoute: InquiriesRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  OfflineRoute: OfflineRoute,
  OverdueRoute: OverdueRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ScheduleRoute: ScheduleRoute,
  ServerErrorRoute: ServerErrorRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  TendersRoute: TendersRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWhatsappBotRoute: AdminWhatsappBotRoute,
  DocumentsInspectionRequestsIdRoute: DocumentsInspectionRequestsIdRoute,
  DocumentsMaterialInspectionRequestsIdRoute:
    DocumentsMaterialInspectionRequestsIdRoute,
  DocumentsMaterialSubmittalsIdRoute: DocumentsMaterialSubmittalsIdRoute,
  DocumentsNcrsIdRoute: DocumentsNcrsIdRoute,
  DocumentsRfisIdRoute: DocumentsRfisIdRoute,
  DocumentsShopDrawingsIdRoute: DocumentsShopDrawingsIdRoute,
  DocumentsSubcontractorApprovalsIdRoute:
    DocumentsSubcontractorApprovalsIdRoute,
  DocumentsTechnicalSubmittalsIdRoute: DocumentsTechnicalSubmittalsIdRoute,
  DocumentsInspectionRequestsIndexRoute: DocumentsInspectionRequestsIndexRoute,
  DocumentsMaterialInspectionRequestsIndexRoute:
    DocumentsMaterialInspectionRequestsIndexRoute,
  DocumentsMaterialSubmittalsIndexRoute: DocumentsMaterialSubmittalsIndexRoute,
  DocumentsNcrsIndexRoute: DocumentsNcrsIndexRoute,
  DocumentsRfisIndexRoute: DocumentsRfisIndexRoute,
  DocumentsShopDrawingsIndexRoute: DocumentsShopDrawingsIndexRoute,
  DocumentsSubcontractorApprovalsIndexRoute:
    DocumentsSubcontractorApprovalsIndexRoute,
  DocumentsTechnicalSubmittalsIndexRoute:
    DocumentsTechnicalSubmittalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
